# Generated by Django 6.0.2 on 2026-02-22 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Агент',
                'verbose_name_plural': 'Агенты',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Телефон')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('role', models.CharField(choices=[('agent', 'Агент'), ('owner', 'Собственник'), ('tenant', 'Арендатор')], default='agent', max_length=20, verbose_name='Роль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('area', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Площадь (м²)')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('total_floors', models.IntegerField(verbose_name='Всего этажей')),
                ('property_type', models.CharField(choices=[('flat', 'Квартира'), ('house', 'Дом'), ('studio', 'Студия'), ('commercial', 'Коммерческое')], max_length=20, verbose_name='Тип')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('archived', 'В архиве'), ('rented', 'Сдан')], default='active', max_length=20, verbose_name='Статус')),
                ('main_image', models.URLField(blank=True, verbose_name='Главное фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_properties', to='agents.user')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_properties', to='agents.user')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма аренды (₽)')),
                ('has_insurance', models.BooleanField(default=False, verbose_name='Страховка оформлена')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('owner_pending', 'Ожидание подписи собственника'), ('tenant_pending', 'Ожидание подписи арендатора'), ('completed', 'Завершена')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_deals', to='agents.agent', verbose_name='Агент')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='agents.property', verbose_name='Объект')),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='owner_deals', to='agents.user', verbose_name='Собственник')),
                ('tenant', models.ForeignKey(limit_choices_to={'role': 'tenant'}, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_deals', to='agents.user', verbose_name='Арендатор')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to='agents.user', verbose_name='Пользователь'),
        ),
    ]
