# Generated by Django 6.0.2 on 2026-02-21 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма аренды (₽)')),
                ('has_insurance', models.BooleanField(default=False, verbose_name='Страховка оформлена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата сделки')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='agents.agent', verbose_name='Агент')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
            },
        ),
    ]
